# BELECTRON 
import time
from colorama import Fore,init
import os
print(Fore.GREEN+"\n L o a d i n g  . . . ")
time.sleep(2.0)

time.sleep(1.0)
print("__________")
time.sleep(0.7)
print("%_________")
time.sleep(0.6)
print("%%________")
time.sleep(0.5)
print("%%%_______")
time.sleep(0.4)
print("%%%%______")
time.sleep(0.3)
print("%%%%%_____")
time.sleep(0.2)
print("%%%%%%____")
time.sleep(0.1)
print ("%%%%%%%___")
time.sleep(0.5)
print ("%%%%%%%%__")
time.sleep(0.1)
print ("%%%%%%%%%_")
time.sleep(0.1)
print ("%%%%%%%%%%")
print ("")

print(Fore.MAGENTA+"\n ````````````````````````````````````````````````````````````````` ")
print(Fore.LIGHTRED_EX+"\n                      .-.                       ")
print(Fore.LIGHTRED_EX+"\n                     (o.o)                       ")
print(Fore.LIGHTRED_EX+"\n                      |=|                         ")
print(Fore.LIGHTRED_EX+"\n                     __|__                        ")
print(Fore.LIGHTRED_EX+"\n                   //.=|=.\\                      ")
print(Fore.LIGHTRED_EX+"\n                  // .=|=. \\                      ")
print(Fore.LIGHTRED_EX+"\n                  \\ .=|=. //                     ")
print(Fore.LIGHTRED_EX+"\n                    (:| |:)                      ")
print(Fore.LIGHTRED_EX+"\n                     || ||                       ")
print(Fore.LIGHTRED_EX+"\n                     () ()                        ")
print(Fore.LIGHTRED_EX+"\n                     || ||                       ")
print(Fore.LIGHTRED_EX+"\n                     || ||                       ")
print(Fore.LIGHTRED_EX+"\n                l42 ==' '==                       ")
time.sleep(1.2)
print(Fore.MAGENTA+"\n ````````````````````````````````````````````````````````````````` ")
print(" ")

print(Fore.BLUE+"\n                            Created By BELECTRON . !                  ")
print(Fore.GREEN+"\n       ID RUBIKA ~ @Creator_Tomaran - @Seyed_xxx  ***  ID CHANNEL ~ @Belectron_bot ")
time.sleep(1.2)
print(Fore.MAGENTA+"\n ````````````````````````````````````````````````````````````````` ")
time.sleep(1.0)
print(" ")

up = int(input("Type 1 for get Code ->->-> "))
print(Fore.RED+"\n  code    👉 (/python2_2.7.17-1_netbot.py-warn%%_000)   👈 ")
print(" ")
time.sleep(1)

print(Fore.BLUE+"\n If you want to update the code, type 2 .>.>.> ")
time.sleep(1.2)
print(" ")

up = int(input("Type 2 for get New Code Or if you do not want new code, type Ctrl+c  ->->-> "))
print(Fore.RED+"\n  New code    👉 (/F./h.d.g.h.h.h/.1.4.6.7)   👈 ")
print(Fore.RED+"\n  New code    👉 (.../proot_5.1.107-38_&^0000-ch64.deb.1.2.0.)  👈 ")
time.sleep(1.2)
print(" ")

print (Fore.YELLOW+"\n ⚠️ Attention ⚠️ ")
print(" 📌 Send this ( / ) in the private chat of the target, then enter the code in other reports.")
print(" ")
time.sleep(1)

print(Fore.CYAN+"\n -------------------------------------------------------------------- ")
exit
